// Demo book data
window.books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    status: "Available",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    status: "Borrowed",
  },
  {
    id: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    status: "Available",
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    status: "Borrowed",
  },
  {
    id: 5,
    title: "Moby-Dick",
    author: "Herman Melville",
    genre: "Adventure",
    status: "Available",
  },
  {
    id: 6,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
    status: "Available",
  },
  {
    id: 7,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    status: "Borrowed",
  },
  {
    id: 8,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    genre: "Romance",
    status: "Available",
  },
  {
    id: 9,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    status: "Available",
  },
  {
    id: 10,
    title: "War and Peace",
    author: "Leo Tolstoy",
    genre: "Historical",
    status: "Borrowed",
  },
];
